AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  mobifone-export-report

  Sample SAM Template for mobifone-export-report
  
Globals:
  Function:
    Runtime: nodejs14.x
    Timeout: 15
    Handler: app.lambdaHandler
    Environment:
      Variables:
        DB_HOST: ci-dev-01.cennywp6tvhb.ap-southeast-1.rds.amazonaws.com
        DB_USER: admin
        DB_PASS: ProudVietnam11235813
        DB_DATABASE: Mobifone

Resources:
  SubServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/subservice/
      Role: arn:aws:iam::562564930891:role/MozularLambdaRole
      VpcConfig:
        SecurityGroupIds:
          - sg-0386a093940f81f67
        SubnetIds:
          - subnet-0e792801143696144
      Events:
        SubService:
          Type: Api 
          Properties:
            Path: /subservice
            Method: get

  FeedbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/feedback/
      Role: arn:aws:iam::562564930891:role/MozularLambdaRole
      VpcConfig:
        SecurityGroupIds:
          - sg-0386a093940f81f67
        SubnetIds:
          - subnet-0e792801143696144
      Events:
        Feedback:
          Type: Api 
          Properties:
            Path: /feedback
            Method: get 

  ThreeCompaniesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/three-companies/
      Role: arn:aws:iam::562564930891:role/MozularLambdaRole
      VpcConfig:
        SecurityGroupIds:
          - sg-0386a093940f81f67
        SubnetIds:
          - subnet-0e792801143696144
      Events:
        ThreeCompanies:
          Type: Api 
          Properties:
            Path: /three-companies
            Method: get 

  VNCertFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/vncert/
      Role: arn:aws:iam::562564930891:role/MozularLambdaRole
      VpcConfig:
        SecurityGroupIds:
          - sg-0386a093940f81f67
        SubnetIds:
          - subnet-0e792801143696144
      Events:
        VNCert:
          Type: Api 
          Properties:
            Path: /vncert
            Method: get          

Outputs:
  SubServiceApi:
    Description: "API Gateway endpoint URL for Prod stage for SubService function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/subservice/"
